server:
  port: 9001

logging:
  level:
    root: info

security:
  jwt:
    token:
      secret-key: secret
      expire-length: 604800000  # ms. 3600000=1h. 604800000=1week

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wext_db
    username: root
    password:
  jpa:
    show-sql: false
  application:
    name: auth-service

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8061/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

wext:
  keyTTL:
    tokenMaxTTL: ${security.jwt.token.expire-length}
