server:
  port: 9001

logging:
  level:
    root: info

security:
  jwt:
    token:
      secret-key: secret
      expire-length: 3600000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wext_db
    username: root
    password:
  jpa:
    show-sql: false

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8061/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

wext:
  keyTTL:
    tokenMaxTTL: 3600000