server:
  port: 9004

spring:
  redis:
    host: localhost
    port: 6379
    password:
  main:
    allow-bean-definition-overriding: true

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8061/eureka/

logging:
  level:
    root: debug

feign:
  client:
    config:
      default:
        connectTimeout: 8000
        readTimeout: 8000
        loggerLevel: basic