server:
  port: 9002

logging:
  level:
    root: info

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wext_db
    username: root
    password:
  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: neo4j
  jpa:
    show-sql: false
  main:
    allow-bean-definition-overriding: true

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8061/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 8000
        readTimeout: 8000
        loggerLevel: basic