server:
  port: 9003

logging:
  level:
    root: info

spring:
  redis:
    host: localhost
    port: 6379
    password:
  datasource:
    url: jdbc:mysql://localhost:3306/wext_db
    username: root
    password:
  jpa:
    show-sql: true
  main:
    allow-bean-definition-overriding: true

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8061/eureka/

servlet:
  multipart:
    max-file-size: -1
    max-request-size: -1
upload:
  img-absolute-path: D://Study/Java/wext/src/main/resources/static/imgs/
  img-path: /images/
  img-max-size: 10485760  # 10Mb

feign:
  client:
    config:
      default:
        connectTimeout: 8000
        readTimeout: 8000
        loggerLevel: basic

wext:
  keyTTL:
    hot-path-cache-hours: 12
  path:
    hot-path-validDataHours: 4320 # 24 * 30 * 6
