server:
  port: 9100

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8061/eureka/

logging:
  level:
    root: info

feign:
  client:
    config:
      default:
        connectTimeout: 8000
        readTimeout: 8000
        loggerLevel: basic

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: auth_route
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: user_route
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - name: AuthFilter
              args:
                excludePaths:
                  - ^\/user\/[^\/]+\/(following|followers|likes)\/?$
                allowEmptyToken:
                  - ^\/user\/[^\/]+\/info\/?$
        - id: wext_get_route
          uri: lb://wext-service
          predicates:
            - Path=/wext/*
            - Method=GET
        - id: wext_route
          uri: lb://wext-service
          predicates:
            - Path=/wext/**
          filters:
            - name: AuthFilter
              args:
                excludePaths:
                  - ^\/wext\/[^\/]+\/(comments|likes)\/?$
        - id: path_route
          uri: lb://wext-service
          predicates:
            - Path=/path/**
        - id: timeline_route
          uri: lb://feed-service
          predicates:
            - Path=/timeline/**
          filters:
            - name: AuthFilter
              args:
                excludePaths:
                  - ^\/timeline\/user\/[^\/]+\/?$
                  - ^\/timeline\/path\/.* # /path/**
        - id: dm_route
          uri: lb://user-service
          predicates:
            - Path=/message/**
          filters:
            - name: AuthFilter
        - id: upload_route
          uri: lb://resources-service
          predicates:
            - Path=/upload/**
          filters:
            - name: AuthFilter
        - id: options_route
          uri: http://0.0.0.0
          order: -1
          predicates:
            - Method=OPTIONS
          filters:
            - name: OptionsFilter
        - id: resources_route
          uri: lb://resources-service
          predicates:
            - Path=/images/**
        - id: PR_route
          uri: lb://wext-service
          order: 2
          predicates:
            - Path=/path_request/**
          filters:
            - name: AuthFilter
        - id: PR_Manage_route
          uri: lb://wext-service
          order: 1
          predicates:
            - Path=/path_request/manage/**
          filters:
            - name: ManagerAuthFilter
  application:
    name: gateway-service
