server:
  port: 9004

spring:
  redis:
    host: localhost
    port: 6379
    password:
  main:
    allow-bean-definition-overriding: true
  application:
    name: feed-service

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8061/eureka/

logging:
  level:
    root: info
    com:
      wext: info


feign:
  client:
    config:
      default:
        connectTimeout: 8000
        readTimeout: 8000
        loggerLevel: basic

wext:
  keyTTL:
    pathFeed: 300 # 5 min
    wextItem: 300 # 5 min
    userEntity: 300 # 5 min
    timelineFeed: 300 # 5 min
