server:
  port: 9005

logging:
  level:
    root: info

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8061/eureka/


upload:
  img-absolute-path: D://Study/Java/wextcould/resources-service/src/main/resources/static/imgs/
  img-path: /images/
  img-max-size: 10485760  # 10Mb

spring:
  application:
    name: resources-service
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
